name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  id-token: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Prepare
        run: cd packages/react-native-background-remover && yarn prepare

      - name: Publish
        run: cd packages/react-native-background-remover && npm publish --provenance --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
